# Generated by Django 5.1.4 on 2024-12-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('emp_salary', models.PositiveIntegerField(default=0, verbose_name='Employee Salary')),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='employee_app.employee')),
            ],
        ),
    ]
