# Generated by Django 4.0.1 on 2024-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_author_employee_age_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Author Name')),
                ('authors', models.ManyToManyField(to='employee_app.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
