# Generated by Django 4.0.1 on 2024-12-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='author_books', to='employee_app.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Book Name'),
        ),
    ]
